plugins {
  id 'java'
  id 'org.springframework.boot' version '3.4.2'
  id 'io.spring.dependency-management' version '1.1.6'
  id 'org.graalvm.buildtools.native' version '0.10.3'
  id 'org.cyclonedx.bom' version '1.10.0'
  id 'io.spring.javaformat' version '0.0.43'
  id "io.spring.nohttp" version "0.0.11"
  id 'jacoco'
}

jacoco {
  toolVersion = "0.8.11"
  reportsDirectory = layout.buildDirectory.dir('jacocoReportsDir')
}

apply plugin: 'java'
apply plugin: 'checkstyle'
apply plugin: 'io.spring.javaformat'

gradle.startParameter.excludedTaskNames += [ "checkFormatAot", "checkFormatAotTest" ]

group = 'org.springframework.samples'
version = '3.4.0'

java {
  sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
  mavenCentral()
}

ext.checkstyleVersion = "10.20.1"
ext.springJavaformatCheckstyleVersion = "0.0.43"
ext.webjarsLocatorLiteVersion = "1.0.1"
ext.webjarsFontawesomeVersion = "4.7.0"
ext.webjarsBootstrapVersion = "5.3.3"

dependencies {
  // Workaround for AOT issue (https://github.com/spring-projects/spring-framework/pull/33949) -->
  implementation 'io.projectreactor:reactor-core'

  implementation 'org.springframework.boot:spring-boot-starter-cache'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'javax.cache:cache-api'
  implementation 'jakarta.xml.bind:jakarta.xml.bind-api'
  runtimeOnly 'org.springframework.boot:spring-boot-starter-actuator'
  runtimeOnly "org.webjars:webjars-locator-lite:${webjarsLocatorLiteVersion}"
  runtimeOnly "org.webjars.npm:bootstrap:${webjarsBootstrapVersion}"
  runtimeOnly "org.webjars.npm:font-awesome:${webjarsFontawesomeVersion}"
  runtimeOnly 'com.github.ben-manes.caffeine:caffeine'
  runtimeOnly 'com.h2database:h2'
  runtimeOnly 'com.mysql:mysql-connector-j'
  runtimeOnly 'org.postgresql:postgresql'
  developmentOnly 'org.springframework.boot:spring-boot-devtools'
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.springframework.boot:spring-boot-testcontainers'
  testImplementation 'org.springframework.boot:spring-boot-docker-compose'
  testImplementation 'org.testcontainers:junit-jupiter'
  testImplementation 'org.testcontainers:mysql'
  checkstyle "io.spring.javaformat:spring-javaformat-checkstyle:${springJavaformatCheckstyleVersion}"
  checkstyle "com.puppycrawl.tools:checkstyle:${checkstyleVersion}"

  // Custom integrationTestImplementation usage example
  //  integrationTestImplementation 'org.testcontainers:postgresql:1.19.0'
}


tasks.named('test') {
  useJUnitPlatform()
  exclude '**/integrationTests/**'
}

checkstyle {
  configDirectory = project.file('src/checkstyle')
  configFile = file('src/checkstyle/nohttp-checkstyle.xml')
}

checkstyleNohttp {
  configDirectory = project.file('src/checkstyle')
  configFile = file('src/checkstyle/nohttp-checkstyle.xml')
}

jacocoTestReport {
  dependsOn test // Depends on 'test' task
  reports {
    xml.required = false
    csv.required = false
    html.required = true
    html.outputLocation = layout.buildDirectory.dir('reports/jacoco/test')
  }

  // Exclusion of files from the analysis
  afterEvaluate {
    classDirectories.setFrom(files(classDirectories.files.collect {
      fileTree(dir: it, exclude: [
        '**/model/**',       // Ignore DTO/models
        '**/config/**',     // Ignore configs
        '**/generated/**',    // Ignore generated code
        '**/exception/**',   // Ignore exceptions
      ])
    }))
  }
}

sourceSets {
  integrationTest {
    java {
      // Добавляем к classpath:
      //    - Скомпилированные классы основного кода (main.output) - .class
      //    - Зависимости для запуска тестов (testRuntimeClasspath)
      compileClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
      // Runtime classpath включает:
      //    - Скомпилированные тесты (output)
      //    - Всё из compileClasspath
      runtimeClasspath += output + compileClasspath
      srcDir file('src/test/java')
    }
//    resources.srcDir file('src/integrationTest/resources')
  }
}

configurations {
  integrationTestImplementation.extendsFrom testImplementation
  integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
}

task integrationTest(type: Test) {
  description = 'Runs integration tests.'
  group = 'verification'
  include '**/integrationTests/**'
  testClassesDirs = sourceSets.integrationTest.output.classesDirs
  classpath = sourceSets.integrationTest.runtimeClasspath
  shouldRunAfter test
  useJUnitPlatform()

  // Configure Jacoco to generate execution data for integration tests
  jacoco {
    enabled = true  // Explicitly enable the agent
    destinationFile = layout.buildDirectory.file("jacoco/integrationTest.exec").get().asFile
  }
}

task jacocoIntegrationTestReport(type: JacocoReport) {
  description = 'Generates JaCoCo coverage reports for integration tests.'
  group = 'verification'
  dependsOn integrationTest
// Use execution data (tests execution results) from integrationTest task
  executionData integrationTest
//  executionData file("jacoco/integrationTest.exec")
  sourceSets sourceSets.main // Link to main source files for coverage analysis

  reports {
    xml.required = true  // For CI tools (e.g., SonarQube)
    html.required = true
    html.outputLocation = layout.buildDirectory.dir("reports/jacoco/integrationTest")
  }

  afterEvaluate {
    classDirectories.setFrom(files(classDirectories.files.collect {
      fileTree(dir: it, excludes: [
        "**/config/**",
        "**/entity/**",
        "**/model/**"
      ])
//      fileTree(dir: it, include: [
//        '**/system/**'
//      ])
    }))
  }
}

jacocoTestCoverageVerification {
  violationRules {
    rule {
      limit {
        minimum = 0.5
      }
    }
    rule {
      enabled = true
      element = 'CLASS'
      includes = ['org.springframework.samples.petclinic']
      limit {
        counter = 'LINE'
        value = 'COVEREDRATIO'
        minimum = 0.7
      }
    }
  }
}

task jacocoMergeReports(type: JacocoReport) {
  dependsOn test, integrationTest
  group = 'verification'
  executionData fileTree(layout.buildDirectory).include("jacoco/*.exec") // Merges all .exec files
  sourceSets sourceSets.main

  reports {
    html.required = true
    html.outputLocation = layout.buildDirectory.dir("reports/jacoco/merged")
    xml.required = true
    xml.outputLocation = layout.buildDirectory.file("reports/jacoco/merged/merged_report.xml")
  }

  afterEvaluate {
    classDirectories.setFrom(files(classDirectories.files.collect {
      fileTree(dir: it, excludes: [
        '**/config/**',
        '**/model/**'
      ])
    }))
  }
}

//tasks.register('jacocoMergeReports', JacocoReport) { }

// Связываем задачи
check.dependsOn integrationTest // Ensure integration tests run during `./gradlew check`
check.dependsOn jacocoTestCoverageVerification
test.finalizedBy jacocoTestReport // Auto-generate unit test report
integrationTest.finalizedBy jacocoIntegrationTestReport // Auto-generate integration test report
check.finalizedBy jacocoMergeReports // Auto-generate merged test report



tasks.named("formatMain").configure { dependsOn("checkstyleMain") }
tasks.named("formatMain").configure { dependsOn("checkstyleNohttp") }

tasks.named("formatTest").configure { dependsOn("checkstyleTest") }
tasks.named("formatTest").configure { dependsOn("checkstyleNohttp") }

checkstyleAot.enabled = false
checkstyleAotTest.enabled = false

checkFormatAot.enabled = false
checkFormatAotTest.enabled = false

formatAot.enabled = false
formatAotTest.enabled = false
